apiVersion: apps/v1
kind: Deployment
metadata:
  name: styx-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: styx-frontend
  template:
    metadata:
      labels:
        app: styx-frontend
    spec:
      imagePullSecrets:
        - name: frontend-credentials
      containers:
        - name: styx-frontend
          image: docker.io/robnickmans/peno3
          imagePullPolicy: IfNotPresent
          args:
            - start-server
            - frontend
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
