apiVersion: v1
kind: Service
metadata:
  name: frontend-api
spec:
  type: NodePort
  selector:
    app: styx-frontend
  ports:
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30090
      targetPort: 3000
