apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/prisma
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-47-f2ea6dda845c97864aa3b826f22473c50bdcfd57 # {"$imagepolicy": "flux-system:styx-backend:tag"}
