apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/prisma
- ../../base/image/prisma
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-19-c6f88dccb6329a54a9a2ba16cf755776b51a2935 # {"$imagepolicy": "flux-system:styx-backend:tag"}
