apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
  - name: backend-config
    literals:
    - DATABASE_URL="file:./prod.db"
generatorOptions:
  disableNameSuffixHash: true
  