apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
  - name: backend-config
    literals:
    - DATABASE_URL="file:./database/prod.db"
    - JWT_FRONTEND=BNPZFR26krtjPNYxDg1S6HZ4p9JzwwFQKnHLbVdfYCwu3dtmFcx5F2VQ4YR35sTXk1V1P2NRvzT28sWBY2kcpg5HehJj73pA
    - JWT_PYTHON=s9pXejNNUDyUEsSjXrFFMbJdNZm6uzfq9aymgkajKcUaccnQMaBdmqyb4FA859X8J2nMYN8TFHs2vFE1yYsAyVzWYFjHuVtM
generatorOptions:
  disableNameSuffixHash: true
  