apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-33-430349fb02fc850a78f4b706e1038ec4ae447925 # {"$imagepolicy": "flux-system:styx-backend:tag"}
