apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-9-c2be9ca32c59ca041e52d9d9b1c55d1a81cd1899 # {"$imagepolicy": "flux-system:styx-backend:tag"}
