apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-50-46626df1659c5f3b027bf7e650ec2c0acb31f828 # {"$imagepolicy": "flux-system:styx-backend:tag"}
