apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-11-542af17f89e4ff1f473b4021e8728e4054c1535e # {"$imagepolicy": "flux-system:styx-backend:tag"}
