apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-51-a0a9756d5d7ab4d4ae0a215b0a319c99971dde53 # {"$imagepolicy": "flux-system:styx-backend:tag"}
