apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/image/backend
images:
- name: docker.io/nickmansrob1205/peno3
  newName: docker.io/nickmansrob1205/peno3 # {"$imagepolicy": "flux-system:styx-backend:name"}
  newTag: sha-28-2047a835205f0423af3a6da2688a2d6f12313de1 # {"$imagepolicy": "flux-system:styx-backend:tag"}
