apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kustomize-styx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize/backend/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
