apiVersion: v1
kind: Service
metadata:
  name: prisma-api
spec:
  type: NodePort
  selector:
    app: styx-prisma
  ports:
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30081
      targetPort: 5555
