apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: styx-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: styx-frontend
  filterTags:
    pattern: '^sha-(?P<ts>.*)-.+'
    extract: '$ts'
  policy:
    numerical:
      order: asc
      