apiVersion: apps/v1
kind: Deployment
metadata:
  name: styx-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: styx-backend
  template:
    metadata:
      labels:
        app: styx-backend
    spec:
      imagePullSecrets:
        - name: backend-credentials
      containers:
        - name: styx-backend
          image: nickmansrob1205/peno3:sha-5-665229e91ff7dc29d543c2584f61ef35755dbc83
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
