apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-15-e615eb6f8f3f5f7cdd101973f3f9a9f2d0de6c6c # {"$imagepolicy": "flux-system:styx-frontend:tag"}
