apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-19-b0d85c8fa5581a4ea175dc2c30a82a1d09a6a90a # {"$imagepolicy": "flux-system:styx-frontend:tag"}
