apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-16-230285a33a83c18dd40903fa0edc79724f110a15 # {"$imagepolicy": "flux-system:styx-frontend:tag"}
