apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-14-1da7e902d91ea0ef70e851887bf56200ceb23a8f # {"$imagepolicy": "flux-system:styx-frontend:tag"}
