apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-21-822a326c48e4f9d371a5c700a418b0148f5cf031 # {"$imagepolicy": "flux-system:styx-frontend:tag"}
