apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../../base/image/frontend
images:
- name: docker.io/robnickmans/peno3
  newName: docker.io/robnickmans/peno3 # {"$imagepolicy": "flux-system:styx-frontend:name"}
  newTag: sha-18-0b5f5a46e6dc5ba3e8722b194be1573c0b26ab0c # {"$imagepolicy": "flux-system:styx-frontend:tag"}
